apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 3
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: rubenernst/kubernetes-user-service:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-proxy-deployment
spec:
  selector:
    matchLabels:
      app: user-service-proxy
  replicas: 3
  template:
    metadata:
      labels:
        app: user-service-proxy
    spec:
      containers:
      - name: user-service-proxy
        image: rubenernst/kubernetes-user-service-proxy:1.0.0
        env:
        - name: USER_SERVICE_HOST
          value: "user-service-service.default.svc.cluster.local"
        - name: USER_SERVICE_PORT
          value: "8080"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-proxy-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: user-service-proxy