apiVersion: v1
kind: Pod
metadata:
  name: playground
  labels:
    app: playground
spec:
  containers:
  - name: playground
    image: rubenernst/kubernetes-playground:1.0.1
    ports:
    - containerPort: 8080