apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
spec:
  selector:
    matchLabels:
      app: playground
  replicas: 3
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: rubenernst/kubernetes-playground:1.0.1
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 25
          periodSeconds: 1